application: wsbtracker
version: 1
runtime: go
api_version: go1

handlers:
- url: /position/.*
  script: _go_app
  login: required

- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app